# Generated by Django 4.1.7 on 2023-03-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tarea',
            field=models.CharField(max_length=90),
        ),
    ]
